title: <p align="center"> ABC XYZ </p>

logo: "images/linkedin_image.jpeg"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nileshchopda/">LinkedIn</a> |
  <a href="https://github.com/nileshchopda">GitHub</a> |
  <a href="https://medium.com/@nilesh.chopda2112">Medium</a>
  </p>
  
  <p align="justify">
  <br><br>
  I am currently working as AI Architect and Data Scientist at Calsoft with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

