title: <p align="center"> Prasad </p>

logo: "images/linkedin_image.jpeg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nileshchopda/">LinkedIn</a> |
  <a href="https://github.com/nileshchopda">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in  Analytics at University of Arizona.
  <br><br>
  I am currently working as Lead Data Scientist at upGrad-INSOFE with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
