atitle: <p align="center"> Salman Ahmed </p>

logo: "https://media.licdn.com/dms/image/D4D03AQHQiSiTwiW9rQ/profile-displayphoto-shrink_400_400/0/1666159453918?e=1683763200&v=beta&t=IexZz8KdQKcqMcp-UQV8_oN6EgD995A3jO9JnJfcHX4"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nileshchopda/">LinkedIn</a> |
  <a href="https://github.com/nileshchopda">GitHub</a> |
  <a href="https://medium.com/@nilesh.chopda2112">Medium</a> |
  <a href="https://topmate.io/nilesh_chopda/">Topmate.io
  </p>
  
  <p align="justify">
  <br><br>
  I am currently working as AI Architect and Data Scientist at Calsoft with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

